name: skyhook-golden-cdk

on:
  push:
    branches: [main]
    paths:
      - 'modules/skyhook-golden-cdk/**'
  pull_request:
    branches:
      - main
    paths:
      - 'modules/skyhook-golden-cdk/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Unit tests
        run: yarn coverage

  publish-npm:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # Push/merge only, not on PR
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install
        run: yarn install
      - name: Typescript build
        run: yarn build
      - name: Bump node version
        run: yarn bump
      - name: Publish to NPMJS
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ${{env.working-directory}}/package.json
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.10.0
        with:
          commit_message: Bump ${{env.working-directory}} version
          commit_author: Skyhook Bot <development@skyhookadventure.com>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
